# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktop < Formula
  desc "A top-like tool to display kubernetes workload metrics"
  homepage "https://github.com/vladimirvivien/ktop"
  version "0.3.0"
  license "Apache-2.0 license"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.0/ktop_v0.3.0_darwin_amd64.tar.gz"
      sha256 "fc229f33508216f74e924b055fdb15fcac0f55f0fe0e7152dd1e7b2e3956e062"

      def install
        bin.install "ktop"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.0/ktop_v0.3.0_darwin_arm64.tar.gz"
      sha256 "2faf34b9885743cb9fcecdc48f0ba5985bdf5909d0c22cf0b3f65efec9d8adcd"

      def install
        bin.install "ktop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.0/ktop_v0.3.0_linux_armv6.tar.gz"
      sha256 "db280a3ce0597270af0cb056696f4c613f4c5037a3f318fff55424be8a9983dd"

      def install
        bin.install "ktop"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.0/ktop_v0.3.0_linux_amd64.tar.gz"
      sha256 "d6881b4cd9fbbfbb757526d6e234285e211b7e83888f283c0ffc0b1a5c30df9d"

      def install
        bin.install "ktop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.0/ktop_v0.3.0_linux_arm64.tar.gz"
      sha256 "dc92c57898270ed78ff89d0904f13709f11fcecdd9defe8146541bfae481459d"

      def install
        bin.install "ktop"
      end
    end
  end
end
