# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktop < Formula
  desc "A top-like tool to display kubernetes workload metrics"
  homepage "https://github.com/vladimirvivien/ktop"
  version "0.3.5"
  license "Apache-2.0 license"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.5/ktop_v0.3.5_darwin_arm64.tar.gz"
      sha256 "6641f6a7999fd98a7e90e71870f30adbf68c69868be101a0bd802dd532ee58b2"

      def install
        bin.install "ktop"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.5/ktop_v0.3.5_darwin_amd64.tar.gz"
      sha256 "e8f81f01d2fba46576bf231d95c53a8ba3064fbeee002596726d4e1c1247aab2"

      def install
        bin.install "ktop"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.5/ktop_v0.3.5_linux_amd64.tar.gz"
      sha256 "36151f383564ce2c0665f41cd98152377114a3fe9afcaa76da40840a1ef30cf6"

      def install
        bin.install "ktop"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.5/ktop_v0.3.5_linux_arm64.tar.gz"
      sha256 "4890a1c8601b6c1873557848a0e0dd6f8427385a43b6cd327d207196a841b057"

      def install
        bin.install "ktop"
      end
    end
  end
end
