# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ktop < Formula
  desc "A top-like tool to display kubernetes workload metrics"
  homepage "https://github.com/vladimirvivien/ktop"
  version "0.3.7"
  license "Apache-2.0 license"

  on_macos do
    on_intel do
      url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.7/ktop_v0.3.7_darwin_amd64.tar.gz"
      sha256 "2340e1aca3f200a496f26bb481cbf40a2691ae4fdea2cb9606c2a12417e3c767"

      def install
        bin.install "ktop"
      end
    end
    on_arm do
      url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.7/ktop_v0.3.7_darwin_arm64.tar.gz"
      sha256 "7956837a53adf2176f9cc593168881227142597fe8f8c5669146cc21d682c517"

      def install
        bin.install "ktop"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.7/ktop_v0.3.7_linux_amd64.tar.gz"
        sha256 "608ef549fd58d33fb44e164c486e9263dc2bf9db064222fed23016a646e03a1a"

        def install
          bin.install "ktop"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/vladimirvivien/ktop/releases/download/v0.3.7/ktop_v0.3.7_linux_arm64.tar.gz"
        sha256 "9ccebac390ee7bf4bd22b0737202ec9b36e0633a785012298fef7e20dcddf6f4"

        def install
          bin.install "ktop"
        end
      end
    end
  end
end
