# This file was generated by GoReleaser. DO NOT EDIT.
cask "ktop" do
  name "ktop"
  desc "A top-like tool to display kubernetes workload metrics"
  homepage "https://github.com/vladimirvivien/ktop"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ktop"

  on_macos do
    on_intel do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_darwin_amd64.tar.gz"
      sha256 "aed3c2426d580c4370c58de04daeed53994a4086271134b0cb8a8dfce6c0be7d"
    end
    on_arm do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_darwin_arm64.tar.gz"
      sha256 "b7c1481e10fccc46bc0c2929f07797f0a4cc7ad748ebcebcfe2aa2d135acdb56"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_linux_amd64.tar.gz"
      sha256 "fafd1008298b02960913d45955bca89ebd471ac64d9ae47b0f8196b38b78c7dc"
    end
    on_arm do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_linux_arm64.tar.gz"
      sha256 "62aecd05d091b4ab57a1776ad43511093d3fb9fe161d26510d812725b7e977c0"
    end
  end

  # No zap stanza required
end
