# This file was generated by GoReleaser. DO NOT EDIT.
cask "ktop" do
  name "ktop"
  desc "A top-like tool to display kubernetes workload metrics"
  homepage "https://github.com/vladimirvivien/ktop"
  version "0.5.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ktop"

  on_macos do
    on_intel do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_darwin_amd64.tar.gz"
      sha256 "43688933c2acc8981b1bf07b1c43c442672850502e16cf79755eaa7a39e65eb7"
    end
    on_arm do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_darwin_arm64.tar.gz"
      sha256 "fb26489789dd3cb267c6b51733f1859810b91ed346c558b0004696975835279a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_linux_amd64.tar.gz"
      sha256 "c6feb9391188f8286dcb63ee4c227aaed4a0776e36a34a3e759585960f631ad5"
    end
    on_arm do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_linux_arm64.tar.gz"
      sha256 "da1846f93c7bd712140506dad575ced720d4f1ebdcb9bdca4bbb49d502fa30f5"
    end
  end

  # No zap stanza required
end
