# This file was generated by GoReleaser. DO NOT EDIT.
cask "ktop" do
  name "ktop"
  desc "A top-like tool to display kubernetes workload metrics"
  homepage "https://github.com/vladimirvivien/ktop"
  version "0.5.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ktop"

  on_macos do
    on_intel do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_darwin_amd64.tar.gz"
      sha256 "bb658e1c79b070e36c39c48f173a9a1b063e2c2b84b3afd581211b8419c0a054"
    end
    on_arm do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_darwin_arm64.tar.gz"
      sha256 "fa8688b99974c55080d27abb1fb4a1796af5deb59c3c735d482720384c43f456"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_linux_amd64.tar.gz"
      sha256 "f8104e5d09bb764da014ba87e5f75c73f55a26b907e9699f43176848a33dbea6"
    end
    on_arm do
      url "https://github.com/vladimirvivien/ktop/releases/download/v#{version}/ktop_v#{version}_linux_arm64.tar.gz"
      sha256 "448e574bead68b3bfeb745493a031015dfd7b3135af6e1a38eadf07c94d087be"
    end
  end

  # No zap stanza required
end
